# Generated by Django 3.1.7 on 2021-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20210312_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='category',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
